# Generated by Django 3.2 on 2023-02-24 15:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(default='', max_length=80)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DescripcionCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosValidacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codreg_proveedor', models.CharField(max_length=50, unique=True)),
                ('proveedor', models.CharField(max_length=80, unique=True)),
                ('correo', models.CharField(max_length=200)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SedesCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codreg_sede', models.CharField(default='', max_length=30)),
                ('nom_sede', models.CharField(default='', max_length=30)),
                ('codreg_ips', models.CharField(default='', max_length=30)),
                ('direccion', models.CharField(default='', max_length=200)),
                ('telefono', models.CharField(default='', max_length=120)),
                ('departamento', models.CharField(default='', max_length=120)),
                ('municipio', models.CharField(default='', max_length=120)),
                ('zona', models.CharField(default='', max_length=120)),
                ('sede', models.CharField(default='', max_length=120)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
            options={
                'unique_together': {('codreg_sede', 'nom_sede')},
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('area', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aareasSolicitudes', to='solicitud.areas')),
            ],
        ),
        migrations.CreateModel(
            name='TiposCompra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_identificacion', models.CharField(max_length=30)),
                ('nom_usuario', models.CharField(max_length=150)),
                ('clave_usuario', models.CharField(max_length=20)),
                ('carg_usuario', models.CharField(max_length=80)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('sede', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssedesCompra', to='solicitud.sedescompra')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudesDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('producto', models.CharField(default='', max_length=30)),
                ('justificacion', models.CharField(default=0, max_length=250)),
                ('especificacionesTecnicas', models.CharField(default='', max_length=300)),
                ('especificacionesAlmacen', models.CharField(default='', max_length=300)),
                ('solicitadoAlmacen', models.IntegerField(default=0)),
                ('entregadoAlmacen', models.IntegerField(default=0)),
                ('especificacionesCompras', models.CharField(default='', max_length=300)),
                ('estadoreg', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1)),
                ('descripcion', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ddescripcion', to='solicitud.descripcioncompra')),
                ('estadosAlmacen', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eestadosAlmacen', to='solicitud.estadosvalidacion')),
                ('estadosCompras', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eestadosCompras', to='solicitud.estadosvalidacion')),
                ('estadosSolicitud', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eestadosSolicitud', to='solicitud.estadosvalidacion')),
                ('estadosValidacion', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eestadosValidacion', to='solicitud.estadosvalidacion')),
                ('presentacion', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ppresentacion', to='solicitud.presentacion')),
                ('solicitud', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssolicitudes', to='solicitud.solicitudes')),
                ('tiposCompra', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ttipoCompra', to='solicitud.tiposcompra')),
                ('usuarioResponsableAlmacen', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uusuariosResponsableAlmacen', to='solicitud.usuarios')),
                ('usuarioResponsableCompra', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uusuariosResponsableCompra', to='solicitud.usuarios')),
                ('usuarioResponsableValidacion', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uusuariosResponsable', to='solicitud.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='usuarios',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uusuarios', to='solicitud.usuarios'),
        ),
        migrations.AddField(
            model_name='areas',
            name='sede',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ssedesArea', to='solicitud.sedescompra'),
        ),
    ]
